# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  azure-servicebus-connector:
    demo:
      connectionString: 'Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;'
    queue1:
      inherit: 'demo'
      queueName: 'queue.1'
    queue2:
      inherit: 'demo'
      queueName: 'queue.2'
    topic1:
      inherit: 'demo'
      topicName: 'topic.1'
      subscriptionName: 'subscription.1'
    