# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  azure-servicebus-connector:
    demo:
      fullyQualifiedNamespace: ''
    demo1:
      inherit: 'demo'
      queueName: 'demo1'
    demo2:
      inherit: 'demo'
      queueName: 'demo2'
    demo3:
      inherit: 'demo'
      topicName: 'demo3'
      subscriptionName: 'demosubscription'
    