# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  azure-servicebus-connector:
    demo:
      inherit: 'standard'
      connection-string: ''
    demo1:
      inherit: 'demo'
      queue: 'demo1'
    demo2:
      inherit: 'demo'
      queue: 'demo2'
    